### ISSUE TITLE
Error in parse_datetime(stop_datetime, tz = tz) : Unexpected type for x

### ISSUE THREAD

**Issue by Maryl86** [rethomics/damr#32] opened 2020-11-15 11:49 UTC
I am trying follow the code on this web page "https://rethomics.github.io/damr.html#zt0" using the example data, but when I try to use the "load_dam" function I am getting the folowin error:

dt <- load_dam(metadata)

Error in parse_datetime(stop_datetime, tz = tz) : Unexpected type for x
I want to know how to fix this problem

this is the code I used :

setwd(DATA_DIR)
 metadata <- fread("metadata.csv")
 metadata <- link_dam_metadata(metadata, result_dir = DATA_DIR) 
   dt <- load_dam(metadata)
###Error in parse_datetime(stop_datetime, tz = tz) : Unexpected type for x

**Comment by qgeissmann** [comment] 2020-11-16 07:42
Hi @Maryl86, thanks for reporting your issue!
It looks like a duplicate of https://github.com/rethomics/damr/issues/29. I will try to update the package to CRAN today. meanwhile, can you try installing the github version?

**Comment by qgeissmann** [comment] 2020-11-16 09:19
our package on its way to CRAN. should be available in a few hours. let me know if this fixes your issue :crossed_fingers:

**Closed** 2021-09-08 17:22 UTC
